name: Build macos intel release

on:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: macos-13
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Instal Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 5.12.12
          archives: qtbase qttools qtsvg qtimageformats

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git ~/vcpkg
          ~/vcpkg/bootstrap-vcpkg.sh
          echo "set(VCPKG_BUILD_TYPE release)" >> ~/vcpkg/triplets/x64-osx.cmake

      - name: Install deps
        run: >
          ~/vcpkg/vcpkg install
          libjpeg-turbo libpng tiff[core,zip,jpeg] openjpeg eigen3 exiv2
          boost-array boost-bind boost-dynamic-bitset boost-foreach
          boost-function boost-intrusive boost-lambda boost-multi-index
          boost-tuple boost-optional boost-random

      - name: Configure
        run: >
          cmake
          -B build
          -D CMAKE_CONFIGURATION_TYPES=Release
          -D CMAKE_TOOLCHAIN_FILE=~/vcpkg/scripts/buildsystems/vcpkg.cmake
          -D CPACK_GENERATOR=TGZ
          -D ENABLE_EXIV2=ON
          -D ENABLE_OPENJPEG=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Pack
        run: cmake --build build --target package

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/scantailor-deviant-*.tar.gz
