name: Build linux release

on:
  workflow_dispatch:

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          sudo apt-get install -y qtbase5-dev qttools5-dev libqt5svg5-dev
          sudo apt-get install -y libboost-dev
          sudo apt-get install -y zlib1g-dev libjpeg-dev libpng-dev libtiff-dev
          sudo apt-get install -y libcanberra-dev libopenjp2-7-dev
          sudo apt-get install -y libexiv2-dev libeigen3-dev

      - name: Configure
        run: |
          cmake \
            -B build \
            -G Ninja \
            -D CMAKE_BUILD_TYPE=Release \
            -D ENABLE_EXIV2=ON \
            -D ENABLE_OPENJPEG=ON \
            -D CPACK_GENERATOR=DEB

      - name: Build
        run: cmake --build build --parallel

      - name: Pack
        run: cmake --build build --target package

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/scantailor-deviant-*.deb
